// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/bluesky': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bluesky.post').default>>>>
    }
    '/api/og/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/og/[id].get').default>>>>
    }
    '/api/questions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions.post').default>>>>
    }
    '/api/questions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/questions/[id].patch').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}